apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: default
  annotations:
    kubernetes.io/service-account.name: default
  labels:
    app: todo-app
stringData:
  .dockerconfigjson: |
    {"auths":{"ghcr.io":{"username":"YnVkZGVzcmVl","password":"Z2hwX3M2dmF4VTl0OEY0U3FncFhXTGNqTVRtenNXOElXNTRkWkhPUw==","email":"budde.sree@gmail.com"}}}
type: kubernetes.io/dockerconfigjson