apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: default
  annotations:
    kubernetes.io/service-account.name: default
  labels:
    app: todo-app
stringData:
  .dockerconfigjson: |
    {"auths":{"ghcr.io":{"username":"<username>","password":"<personal-access-token>","email":"<email>"}}}
type: kubernetes.io/dockerconfigjson