name: Publish Helm Chart to GHCR

on:
  push:
    branches:
      - main
    paths:
      - '/helm-charts/todoapp/**'           # Your chart folder path
      - '.github/workflows/helm-publish.yaml'

env:

  TAG: ${{ github.sha }} 
      
jobs:
  helm:
    name: Package & Push Helm Chart
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.13.0

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | helm registry login ghcr.io -u buddesree --password-stdin



      - name: Package Helm chart
        run: |
          cd helm-charts/todoapp
          helm package . --destination ../charts

      - name: Push chart to GHCR
        run: |
          helm push helm-charts/todoapp/todo-app-*.tgz oci://ghcr.io/${{ github.repository_owner }}/helm-charts/$TAG
